services:
  - type: web
    name: shobdo-kotha
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEEPSEEK_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
